### ISSUE TITLE
Allow use of remote wsdls

### ISSUE THREAD

**Issue by sne11ius** [softvision-dev/webpdf-wsclient#4]
wsdl files are loaded locally by default (see `SoapWebService.getWsdlDocumentLocation()`). It would be nice to have a simple way to load these files from the webpdf server. This would also circumvent problems like in issue #3.

I think two things need to be done to enable this:

1. Add an "official" way to set `SoapSession.useLocalWsdl` to false. Maybe just make the setter public. The flag can already set via reflection, but of course that's not very nice.
2. Fix generation for remote URLs in `SoapWebService.getWsdlDocumentLocation()`. If `useLocalWsdl` is false in this method, it will simply use `this.webserviceURL.toURL()`. However, this URL seems not to be correct, it gives an HTML-Overview. To make it work, the URL needs an additional `?wsdl` to be added.

**Comment by sne11ius** [comment]
No reaction?

**Comment by christianAppl** [comment]
Has been answered in issue #3
